In [1]:
bin(101)

'0b1100101'

# 1 Problem

In [6]:
def isPrime(n):
    for i in range(2,n):
        if n%i==0:
            return False
    return True
isPrime(4)


False

In [7]:
def isemirp(n):
    n=str(n)
    if n==n[::-1]:
        return False
    return isPrime(int(n[::-1]))
isemirp(7)


False

In [9]:
def isbemirp(n):
    n=str(n)
    num=""
    for i in n:
        if i== "6":
            num+="9"
        elif i=="9":
            num+="6"
        else:
            num+=i
    return isemirp(int(num))
isbemirp(101)

False

In [10]:
n=int(input())
for i in range(n):
    num=int(input())
    status= "C"
    if isPrime(num):
        status = "P"
        if isemirp(num):
            status= "E"
            if isbemirp(num):
                status = "B"
    print(status)

4
101
P
1011
C
1061
B
1069
E


# 2 Problem

In [12]:
def sum_of_prime_facts(num):
    s=0
    for i in range(2,num):
        if n%i ==0:
            if isPrime(i):
                s+=1
    return s
n=int(input())
for j in range(n):
    a,b=list(map(int,input().split()))
    print(sum_of_prime_facts(a),sum_of_prime_facts(b))
    if sum_of_prime_facts(a)==sum_of_prime_facts(b):
        print("True")
    else:
        print("False")

4
24 25
1 1
True
49 50
1 1
True
54 67
1 1
True
23 54
1 1
True


# Numpy

Watching your data in one way 

Advantages:
 * strore Same datatype

Package:
 * set of Modules

 
    

In [30]:
import numpy as np   #----> changing highest bytes of datatype (type-casting to all elements) in list
l=[1,2,3,4,5,45.4,"lavanya",34567890123456789012345678904567890]
print(np.array(l))

['1' '2' '3' '4' '5' '45.4' 'lavanya'
 '34567890123456789012345678904567890']


In [22]:
type(np.array(l)) #----> for checking type 

numpy.ndarray

In [28]:
type(int(32))

int

In [37]:
l1=[1,2,3,4,5,[9,8,7,6,0],[1,6,7]]
np.array(l1)


array([1, 2, 3, 4, 5, list([9, 8, 7, 6, 0]), list([1, 6, 7])],
      dtype=object)

In [36]:
li=[1,2,3,4]
print(li+2)

TypeError: can only concatenate list (not "int") to list

In [35]:
li=[1,2,3,4]     #-----------> Vectorized Operation
print(np.array(li)+2)

[3 4 5 6]


In [42]:
np.array(l),dtype='34'

SyntaxError: can't assign to function call (<ipython-input-42-b275fbee3e90>, line 1)

In [ ]:
int,obj,float,str,bool,double 

In [81]:
lp=[[1,6],["0","5","4"]]
a=np.array(lp,dtype="object")
a

array([list([1, 6]), list(['0', '5', '4'])], dtype=object)

In [59]:
a=np.array(lp,dtype="bool")
a

array([ True,  True])

In [65]:
#tolist()
a.tolist()

# Numpy object occupies lesser space than a list in python

[[1, 'lavanya'], [0, 3, 4, 5]]

In [66]:
a

array([list([1, 'lavanya']), list([0, 3, 4, 5])], dtype=object)

In [71]:
a.shape

(2,)

In [70]:
a.dtype

dtype('O')

In [72]:
a.size

2

In [73]:
a.ndim

1