# Numpy Library
    - Processing N-Dimensional arrays

In [5]:
import numpy as np

l=[1,2,3,4,'b'] #--> if any one of element is alpha than output display all elements are in str format else integers
a=np.array(l)
a #----->numpy.ndarray N-dimentional Array
b=np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
rn=np.random.randint(0,100,size=10)
rn

array([89, 46, 95,  8, 81, 13, 71, 66, 79, 27])

In [29]:
m3=np.random.randint(0,100,size=(3,3,3))
m3[2][2]

array([3, 6, 2])

In [30]:
m3.ndim

3

In [31]:
m3.size

27

In [32]:
m3.shape

(3, 3, 3)

In [33]:
m3.dtype

dtype('int32')

In [34]:
m3.nbytes

108